public enum ATMStates {
    READY,
    ENTER_PIN,
    SELECT_OPTION,
    DEPOSIT,
    WITHDRAW,
    DISPLAY_BALANCE,
    CASH_DISPENSED,
    INVALID_CASH_RETURNED,
    ERROR_MESSAGE_DISPLAYED,
    EXIT_MESSAGE_DISPLAYED;
}
